apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate-affinity-webhook
webhooks:
  - name: mutate-affinity-service.castai-agent.svc.cluster.local
    clientConfig:
      service:
        name: mutate-affinity-service
        namespace: castai-agent
        path: "/mutate-pods"
        port: 5050
      caBundle: "None"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchExpressions:
      - key: webhook-enabled
        operator: NotIn
        values: ["false"]
    admissionReviewVersions: ["v1"]
    sideEffects: None