apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutate-affinity
  namespace: castai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutate-affinity
  template:
    metadata:
      labels:
        app: mutate-affinity
    spec:
      serviceAccountName: mutate-affinity-service-account
      containers:
      - name: mutate-affinity-container
        image: lkup77/mutate_affinity:v14
        imagePullPolicy: Always
        ports:
        - containerPort: 5050
#        env:
#        - name: MUTATING_WEBHOOK_LABEL_KEY
#          value: "app"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: "app"
                  operator: In
                  values:
                  - mutate-affinity
              topologyKey: "kubernetes.io/hostname"
