apiVersion: v1
kind: Service
metadata:
  name: mutate-affinity-service
  namespace: castai-agent
spec:
  selector:
    app: mutate-affinity
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
