apiVersion: v1
kind: ServiceAccount
metadata:
  name: mutate-affinity-service-account
  namespace: castai-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: castai-agent
  name: mutate-affinity-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "update", "patch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mutate-affinity-role-binding
  namespace: castai-agent
subjects:
- kind: ServiceAccount
  name: mutate-affinity-service-account
  namespace: castai-agent
roleRef:
  kind: Role
  name: mutate-affinity-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mutate-affinity-cluster-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "update", "patch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mutate-affinity-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: mutate-affinity-service-account
  namespace: castai-agent
roleRef:
  kind: ClusterRole
  name: mutate-affinity-cluster-role
  apiGroup: rbac.authorization.k8s.io

