apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: nginx  # Ensure this matches the criteria for your webhook
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
